"""add discussions table

Revision ID: 59106260892b
Revises: db0bccbcf731
Create Date: 2026-08-23 20:40:06.477376
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '59106260892b'
down_revision: Union[str, None] = 'db0bccbcf731'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discussions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('started_from_row_id', sa.String(length=26), nullable=False),
    sa.Column('row_id', sa.String(length=26), nullable=False),
    sa.Column('messages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discussions_tenant_id'), 'discussions', ['tenant_id'], unique=False)
    op.create_index('ix_discussions_tenant_updated', 'discussions', ['tenant_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_discussions_tenant_updated', table_name='discussions')
    op.drop_index(op.f('ix_discussions_tenant_id'), table_name='discussions')
    op.drop_table('discussions')
    # ### end Alembic commands ###
