"""initial schema

Revision ID: db0bccbcf731
Revises: 
Create Date: 2026-08-21 16:29:58.879258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'db0bccbcf731'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('linkedin_sub', sa.String(length=100), nullable=True),
    sa.Column('picture_url', sa.Text(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan', sa.String(length=40), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('monthly_token_cap', sa.Integer(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linkedin_sub', name='uq_tenants_linkedin_sub')
    )
    op.create_index(op.f('ix_tenants_linkedin_sub'), 'tenants', ['linkedin_sub'], unique=False)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_table('feedback',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('row_id', sa.String(length=26), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('processed', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_tenant_id'), 'feedback', ['tenant_id'], unique=False)
    op.create_table('linkedin_apps',
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('linkedin_tokens',
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=False),
    sa.Column('refresh_expires_at', sa.String(length=40), nullable=False),
    sa.Column('person_urn', sa.String(length=120), nullable=False),
    sa.Column('obtained_at', sa.String(length=40), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('pipeline_rows',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('source_title', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=40), nullable=False),
    sa.Column('theme', sa.String(length=40), nullable=False),
    sa.Column('why_it_matters', sa.Text(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('angle', sa.Text(), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=False),
    sa.Column('revision_note', sa.Text(), nullable=False),
    sa.Column('revision_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('post_urn', sa.String(length=200), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_distance', sa.Float(), nullable=True),
    sa.Column('reach', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_rows_status'), 'pipeline_rows', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_rows_tenant_id'), 'pipeline_rows', ['tenant_id'], unique=False)
    op.create_index('ix_rows_tenant_archived', 'pipeline_rows', ['tenant_id', 'archived_at'], unique=False)
    op.create_index('ix_rows_tenant_status', 'pipeline_rows', ['tenant_id', 'status'], unique=False)
    op.create_table('settings',
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'key')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=40), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_tenant_id'), 'sources', ['tenant_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('job', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_events_period'), 'usage_events', ['period'], unique=False)
    op.create_index(op.f('ix_usage_events_tenant_id'), 'usage_events', ['tenant_id'], unique=False)
    op.create_index('ix_usage_tenant_period', 'usage_events', ['tenant_id', 'period'], unique=False)
    op.create_table('voice_amendments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rule', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('recurring', sa.Boolean(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('applied', sa.String(length=80), nullable=False),
    sa.Column('source_row_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_amendments_tenant_id'), 'voice_amendments', ['tenant_id'], unique=False)
    op.create_table('voice_cards',
    sa.Column('tenant_id', sa.String(length=26), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voice_cards')
    op.drop_index(op.f('ix_voice_amendments_tenant_id'), table_name='voice_amendments')
    op.drop_table('voice_amendments')
    op.drop_index('ix_usage_tenant_period', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_tenant_id'), table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_period'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_sources_tenant_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_table('settings')
    op.drop_index('ix_rows_tenant_status', table_name='pipeline_rows')
    op.drop_index('ix_rows_tenant_archived', table_name='pipeline_rows')
    op.drop_index(op.f('ix_pipeline_rows_tenant_id'), table_name='pipeline_rows')
    op.drop_index(op.f('ix_pipeline_rows_status'), table_name='pipeline_rows')
    op.drop_table('pipeline_rows')
    op.drop_table('linkedin_tokens')
    op.drop_table('linkedin_apps')
    op.drop_index(op.f('ix_feedback_tenant_id'), table_name='feedback')
    op.drop_table('feedback')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_linkedin_sub'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
